FROM itdoginfo/openwrt-sdk-ipk:24.10.3

ARG PODKOP_VERSION

COPY ./podkop /builder/package/feeds/utilities/podkop
COPY ./luci-app-podkop /builder/package/feeds/luci/luci-app-podkop

RUN export PODKOP_VERSION="v${PODKOP_VERSION}" && \
    make defconfig && \
    make package/podkop/compile V=s -j4 && \
    make package/luci-app-podkop/compile V=s -j4