FROM tokKurumi/openwrt-sdk-cached:latest

COPY ./podkop /builder/package/feeds/utilities/podkop
COPY ./luci-app-podkop /builder/package/feeds/luci/luci-app-podkop

RUN make defconfig && \
    make package/podkop/compile && \
    make package/luci-app-podkop/compile V=s -j4