FROM itdoginfo/openwrt-sdk-apk:25.12.3

ARG NETSHIFT_VERSION
ENV NETSHIFT_VERSION=${NETSHIFT_VERSION}

COPY ./netshift /builder/package/feeds/utilities/netshift
COPY ./luci-app-netshift /builder/package/feeds/luci/luci-app-netshift

RUN make defconfig && \
    make package/netshift/compile -j4 V=s && \
    make package/luci-app-netshift/compile -j4 V=s
