FROM itdoginfo/openwrt-sdk-apk:09102025

COPY ./podkop /builder/package/feeds/utilities/podkop
COPY ./luci-app-podkop /builder/package/feeds/luci/luci-app-podkop

RUN make defconfig && make package/podkop/compile -j4 V=s && make package/luci-app-podkop/compile -j4 V=s