---
name: 🐛 Сообщение об ошибке
description: Создавайте только, если проблема точно не на вашей стороне.
title: "[BUG] "
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Спасибо за создание отчета об ошибке!
        
        Перед отправкой, пожалуйста:
        - Проверьте [существующие issues](https://github.com/yandexru45/netshift/issues)
        - Просмотрите [документацию](https://podkop.net)

  - type: textarea
    id: description
    attributes:
      label: 📝 Описание проблемы
      description: Четкое и краткое описание того, что не работает
      placeholder: Опишите проблему
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Шаги для воспроизведения
      description: Шаги для воспроизведения проблемы. Если вы настраваете что-то по мануалу, приложите ссылку на него.
      placeholder: |
        1. 
        2. 
        3. 
        4. 
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: ✅ Ожидаемое поведение
      description: Четкое и краткое описание того, что должно было произойти
      placeholder: Опишите ожидаемое поведение
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: 🖥️ Информация о системе
      description: |
        Информация о вашей системе (заполните всё применимое)
      value: |
        - **OpenWrt версия**: 
        - **NetShift версия**: 
        - **Роутер модель**: 
        - **Sing-box версия**: 
      render: markdown
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: ⚙️ Конфигурация
      description: |
        Релевантные части конфигурации (удалите чувствительную информацию!)
      placeholder: |
        Например:
        - Содержимое /etc/config/netshift
        - Конфигурация sing-box (если релевантно)
        - Дополнительные конфиги, которые потребуются wireless/network/dhcp и т.д.
      render: shell