#!/bin/sh

rm -f /var/luci-indexcache*
rm -f /tmp/luci-indexcache*
rm -f /tmp/luci-modulecache/*

uci -q set podkop.settings.ui_asset_version='__COMPILED_ASSET_VERSION_VARIABLE__'
uci -q commit podkop

[ -x /etc/init.d/rpcd ] && /etc/init.d/rpcd reload

logger -t "podkop" "$timestamp uci-defaults script executed"

exit 0
